debug: false
charset: UTF-8
locale: en

config:
  database:
    db.options:
      driver:   pdo_mysql
      host:     localhost
      dbname:   database
      user:     user
      password: password
      charset:  utf8
      
  pagination:
    posts_main_page: 10